# CHIPMUNK_INCLUDE_DIR
# CHIPMUNK_LIBRARY
# CHIPMUNK_FOUND

find_path(CHIPMUNK_INCLUDE_DIR NAMES chipmunk/chipmunk.h)
find_library(CHIPMUNK_LIBRARY NAMES chipmunk)

if(CHIPMUNK_LIBRARY AND CHIPMUNK_INCLUDE_DIR)
SET(CHIPMUNK_FOUND TRUE)
else()
SET(CHIPMUBK_FOUND FALSE)
endif()

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(CHIPMUNK DEFAULT_MSG CHIPMUNK_LIBRARY CHIPMUNK_INCLUDE_DIR)

mark_as_advanced(CHIPMUNK_INCLUDE_DIR CHIPMUNK_LIBRARY)
